version: '3'
services: 
    python:
        build: ./python
        container_name: collector_ssh
        volumes:
            - ./app/:/app/
        restart: always
        tty: true
        image: collector_ssh:latest